version: '3.10'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    expose:
      - 3000
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      ROOT_URL: "http://localhost:3000"
      PORT: 3000
      DEPLOY_METHOD: docker
    ports:
      - "0.0.0.0:4000:3000"
    depends_on:
      - mongodb
    restart: on-failure

  mongodb:
    image: docker.io/bitnami/mongodb:latest
    volumes:
      - mongodb_new_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: true
      ALLOW_EMPTY_PASSWORD: yes
    restart: on-failure

volumes:
  mongodb_new_data: { driver: local }
